name: CI

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master
        
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v2
      
      # Run projects tests
      - name: Tests
        run: npm test
        
      # Run build
      - name: Build
        run: npm run build
        
      # Run Stryker-Mutator check
      - name: Stryker-Mutator
        run: npm run test:mutation
        
      # Run chromatic for visual regression test
      - name: Chromatic
        run: npm run chromatic
        
